# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36e2cfdc22bb96bc427ca166c8d22efbce8535fc8fed507ae8dcec4b1c8a1b922f367d996e67c39b7aa89e7c979a097dbbf834ecb20006f65077a546d7cce0b

test:
  secret_key_base: ce8e384f83eb0d52d53bedfa685eb58a318960f9f9eb071de9227b33a2615d6456cb63d8e5b1c75fff080a25b9a0b7a3f4c299f72a63e3144dd796b9573d93d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
